{{- if .Values.wso2.sidecarReq }}
apiVersion: v1
kind: Secret
metadata:
  name: logstash-s3-secrets
data:
  S3_KEY_ID:  {{ .Values.wso2.s3Vars.s3accesskey | b64enc }}
  S3_SECRET_KEY: {{ .Values.wso2.s3Vars.s3secretkey | b64enc }}
{{ end }}
